/*
 * SwingTest.java Created on __DATE__, __TIME__
 */

package com.hazendaz.swing;

import java.util.List;

import javax.enterprise.event.Observes;

import org.jboss.weld.environment.se.bindings.Parameters;
import org.jboss.weld.environment.se.events.ContainerInitialized;

/**
 * @author __USER__
 */
public class SwingTest extends javax.swing.JFrame {

    private static final long serialVersionUID = 1L;

    private javax.swing.JMenuItem aboutMenuItem;

    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;

    /** Creates new form SwingTest */
    public SwingTest() {
        this.initComponents();
    }

    /**
     * @param event
     *            containerInitialized event
     * @param parameters
     *            the command line arguments
     */
    public void main(@Observes final ContainerInitialized event, @Parameters final List<String> parameters) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SwingTest().setVisible(true);
            }
        });
    }

    /**
     * @param evt
     *            awt action event
     */
    void exitMenuItemActionPerformed(final java.awt.event.ActionEvent evt) {
        System.exit(0);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    private void initComponents() {

        this.menuBar = new javax.swing.JMenuBar();
        this.fileMenu = new javax.swing.JMenu();
        this.openMenuItem = new javax.swing.JMenuItem();
        this.saveMenuItem = new javax.swing.JMenuItem();
        this.saveAsMenuItem = new javax.swing.JMenuItem();
        this.exitMenuItem = new javax.swing.JMenuItem();
        this.editMenu = new javax.swing.JMenu();
        this.cutMenuItem = new javax.swing.JMenuItem();
        this.copyMenuItem = new javax.swing.JMenuItem();
        this.pasteMenuItem = new javax.swing.JMenuItem();
        this.deleteMenuItem = new javax.swing.JMenuItem();
        this.helpMenu = new javax.swing.JMenu();
        this.contentsMenuItem = new javax.swing.JMenuItem();
        this.aboutMenuItem = new javax.swing.JMenuItem();

        this.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        this.fileMenu.setText("File");

        this.openMenuItem.setText("Open");
        this.fileMenu.add(this.openMenuItem);

        this.saveMenuItem.setText("Save");
        this.fileMenu.add(this.saveMenuItem);

        this.saveAsMenuItem.setText("Save As ...");
        this.fileMenu.add(this.saveAsMenuItem);

        this.exitMenuItem.setText("Exit");
        this.exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(final java.awt.event.ActionEvent evt) {
                SwingTest.this.exitMenuItemActionPerformed(evt);
            }
        });
        this.fileMenu.add(this.exitMenuItem);

        this.menuBar.add(this.fileMenu);

        this.editMenu.setText("Edit");

        this.cutMenuItem.setText("Cut");
        this.editMenu.add(this.cutMenuItem);

        this.copyMenuItem.setText("Copy");
        this.editMenu.add(this.copyMenuItem);

        this.pasteMenuItem.setText("Paste");
        this.editMenu.add(this.pasteMenuItem);

        this.deleteMenuItem.setText("Delete");
        this.editMenu.add(this.deleteMenuItem);

        this.menuBar.add(this.editMenu);

        this.helpMenu.setText("Help");

        this.contentsMenuItem.setText("Contents");
        this.helpMenu.add(this.contentsMenuItem);

        this.aboutMenuItem.setText("About");
        this.helpMenu.add(this.aboutMenuItem);

        this.menuBar.add(this.helpMenu);

        this.setJMenuBar(this.menuBar);

        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this.getContentPane());
        this.getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 279, Short.MAX_VALUE));

        this.pack();
    }

}
